### ISSUE TITLE
Failing the build

### ISSUE THREAD

**Issue by joehni** [chonton/exists-maven-plugin#1]
Hi Chas,

thanks for this cute plugin! As en enhancement it would be nice to have also the possibility to fail a build.

Cheers,
Jörg

**Comment by cdealti** [comment]
Same requirement here. In our multimodule project we have tenths of individual project versions to maintain/update. We would like to fail the build if an artifact has already been deployed which in our case means we forgot to bump a version.
Currently we have to resort to the enforcer plugin to fail the build based on a property set by the exists plugin.
