### ISSUE TITLE
v0.0.6 uses vulnerable guava

### ISSUE THREAD

**Issue by ENGINEBREATH** [chonton/exists-maven-plugin#12]
Versions of guava <24.1.1 are vulnerable, of which dependency "org.apache.maven:maven-core:jar:3.3.9" is using "com.google.guava:guava:jar:18.0".
The latest I can patch it to is "com.google.guava:guava:jar:23.4-jre"; instances above ('23.5-jre' and beyond) fail the build (https://mvnrepository.com/artifact/com.google.guava/guava).

I tried to patch "org.apache.maven:maven-core:jar:3.3.9" with the latest that still builds "org.apache.maven:maven-core:jar:3.5.4" here - however this still uses "com.google.guava:guava:jar:20.0".

If possible can "exists-maven-plugin" be configured to use the latest "org.apache.maven:maven-core:jar:3.6.0", which does not seem to need guava at all (https://mvnrepository.com/artifact/org.apache.maven/maven-core)?

Kind regards!

**Comment by chonton** [comment]
PR welcome

**Comment by chonton** [comment]
0.1.0 updates dependency
