### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [chonton/exists-maven-plugin#13]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/honton/chas/exists/CheckSum.java: Line number => 22: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by chonton** [comment]
Not a misuse.  digest() is invoked on line 31.
