### ISSUE TITLE
exists-maven-plugin v0.1.0 incompatibility with maven 3.3.9 and older

### ISSUE THREAD

**Issue by oliverlockwood** [chonton/exists-maven-plugin#14]
If you try to use v0.1.0 of this plugin on an older version of Maven, you will experience symptoms similar to those described in https://github.com/jeremylong/DependencyCheck/issues/1054.

v0.0.6 continues to work fine.

I had upgraded this after reviewing the output of `mvn versions:display-plugin-updates`; while some new plugin versions specified that they would require a minimum of e.g. 3.5.4, this one did not:

```
[INFO] The following plugin updates are available:
[INFO]   org.honton.chas:exists-maven-plugin ................ 0.0.6 -> 0.1.0
[INFO]
[INFO] Project inherits minimum Maven version as: 3.3.9
[INFO] Plugins require minimum Maven version of: 3.3.9
[INFO]
[INFO] Require Maven 3.5.4 to use the following plugin updates:
[INFO]   org.codehaus.mojo:license-maven-plugin .............. 1.20 -> 2.0.0
```

Perhaps you could ensure that the published plugin compatibility is accurate, to avoid other people encountering the same issue?

Thanks!

**Comment by chonton** [comment]
Thanks for the report.
I've updated the readme to indicate minimum required versions.
Next release will enforce the minimum required versions for java and maven.

**Comment by oliverlockwood** [comment]
Sounds reasonable to me. Since changing and republishing artifacts is generally a Bad Thing, I can't ask for more so I think we can consider this issue closed.

Thanks!
