### ISSUE TITLE
Incorrectly identifies remote artifact as not existing when in fact it does exist

### ISSUE THREAD

**Issue by MaiaTechnology** [chonton/exists-maven-plugin#16]
I have run mvn exists to check if a remote artifact exists and when I click on the URL that is written to stdout by your plugin I can download that artifact using my browser but for some odd reason your plugin thinks the artifact does not exist. Why is that?

[DEBUG] Configuring mojo org.honton.chas:exists-maven-plugin:0.1.0:remote from plugin realm ClassRealm[plugin>org.honton.chas:exists-maven-plugin:0.1.0, parent: sun.misc.Launcher$AppClassLoader@6d6f6e28]
[DEBUG] Configuring mojo 'org.honton.chas:exists-maven-plugin:0.1.0:remote' with basic configurator -->
[DEBUG]   (f) artifact = platform-auth-bdd-1.1.0.jar
[DEBUG]   (f) cmpChecksum = false
[DEBUG]   (f) failIfExists = true
[DEBUG]   (f) failIfNotExists = false
[DEBUG]   (f) failIfNotMatch = true
[DEBUG]   (f) mavenProject = MavenProject: au.com.maiatechnology:platform-auth-bdd:1.1.0 @ /Volumes/Maia/git/platform-auth-ui/bdd/pom.xml
[DEBUG]   (f) project = au.com.maiatechnology:platform-auth-bdd:1.1.0
[DEBUG]   (f) property = maven.deploy.skip
[DEBUG]   (f) repository = https://<url removed>
[DEBUG]   (f) serverId = gitlab-maven
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@64bc21ac
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@5d25e6bb
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipIfSnapshot = true
[DEBUG]   (f) snapshotRepository = <url removed>
[DEBUG]   (f) snapshotServerId = gitlab-maven
[DEBUG]   (f) userProperty = false
[DEBUG] -- end configuration --
[DEBUG] Checking for artifact at <url removed>
[INFO] au.com.maiatechnology:platform-auth-bdd:1.1.0 does not exist

**Comment by MaiaTechnology** [comment]
I think I understand what the issue is...your plugin is not able to use the gitlab token to authenticate. When a user is not authenticated then a 404 is returned and so your plugin thinks the artifact does not exist remotely. Anyway to resolve that?

**Comment by chonton** [comment]
Did you add your personal access token to your settings.xml as documented in [Authenticating with a personal access token]?(https://docs.gitlab.com/ee/user/packages/maven_repository/#authenticating-with-a-personal-access-token)

**Comment by MaiaTechnology** [comment]
Thanks Chas for your quick response.

I already run: mvn deploy using the gitlab CI Job Token method and that works fine. I can see my artifacts inside gitlab's mvn repo. I assumed your mvn plugin would be able to leverage the same authentication mechanism but I'm guessing not? Is it possible to get any debug info on what your plugin is attempting to do in terms of authentication that might un-mask the underlying issue? Or how can I debug your plugin? I looked at your source code and it looks ok at first glance. I'm guessing the issue is somewhere inside the Wagon API code???

**Comment by jeffque** [comment]
Same issue here. I have tweaked the version of my project to match with one already present at artifactory and the plugin returned "does not exist".

AFAIK I should be able to push to my Artifactory with current `settings.xml`, shall test this now

**Comment by jeffque** [comment]
Oops, sorry...

Recently I've changed my `groupId` and had not realized it until `mvn deploy` worked fine. And after that it recognized that the artifact was deployed correctly

**Comment by ToppScorer** [comment]
Hi,

I'm having exactly the same problem with GitLab. 

> 1. Are you able to push to the repository with the current settings.xml?

Yes

> 2. Did you add your personal access token to your settings.xml as documented in Authenticating with a personal access token?

Yes

Why was this ticket closed?

**Comment by chonton** [comment]
Probably same as #27
