### ISSUE TITLE
Wrong artifact ID output when looking for a remote artifact

### ISSUE THREAD

**Issue by jhonny-oliveira** [chonton/exists-maven-plugin#17]
Hi!

Assuming we are on project "mypoc" and we check if a remote artifact ("app-rs-web" in this scenario) the output line will mention "@ mypoc" as opposed to "@ app-rs-web". Having the correct value is convenient for scripting purposes. 

Please check the attachment for further details.

[misleadingOutput.txt](https://github.com/chonton/exists-maven-plugin/files/3656720/misleadingOutput.txt)

Cheers,
Jhonny Oliveira

**Comment by chonton** [comment]
The text @ myproc is maven output of the execution id.
