### ISSUE TITLE
Duplicated results in a multi-project

### ISSUE THREAD

**Issue by jhonny-oliveira** [chonton/exists-maven-plugin#18]
Hi!

exists-maven-plugin outputs duplicated results when checking an artifact in a multi-project.

Please have a look at the attachment for further details.

[multi-project.txt](https://github.com/chonton/exists-maven-plugin/files/3656833/multi-project.txt)

Cheers,
Jhonny Oliveira

**Comment by chonton** [comment]
Since you have configured the plugin to run in each module, maven will execute the plugin for each module.  This is probably what is desired, setting the property in each module to determine if the module's artifact should be deployed/installed.
