### ISSUE TITLE
Question : profile activation

### ISSUE THREAD

**Issue by gigaga** [chonton/exists-maven-plugin#25]
Hello,

There is a possibility to use your plugin to activate a maven profile if a specific dependency doesn't exist ?
I would like to use a dependency with version RELEASE if a specific version (1.0.0 for example) doesn't exist. 

Regards,

**Comment by chonton** [comment]
Profiles conditions are extremely limited and are evaluated before any phases that execute plugins.

An alternative would be to add two properties to the exists-plugin:
- existsValue - the value for the property if the artifact exists
- notExistsValue - the value for the property if the artifact does not exist

Additionally, existsValue and  notExistsValue could be interpolated, allowing build up of a complex final value

However, I do not know of any technique or plugin that can dynamically change dependencies.  You might be able to dynamically add jars to an archive using the assembly plugin.
