### ISSUE TITLE
SNAPSHOT check exists

### ISSUE THREAD

**Issue by gigaga** [chonton/exists-maven-plugin#26]
Hello,

When plugin tries to check SNAPSHOT version from remote server, the url checked is "\<host\>/content/repositories/snapshots/\<groupId\>/\<artifact\>/\<version\>/\<artifact\>-\<version\>.tar.gz"
But when it is a SNAPHOSTversion, the correct url should contain a timestamp in final filename :  \<host\>/content/repositories/snapshots/groupId/artifact/1.0.0-SNAPSHOT/artifact-1.0.0-20210615.181211-10.jar"
where name is "artifact-1.0.0-20210615.181211-10.jar" and not "artifact-1.0.0-SNAPSHOT.jar".

Regards,

**Comment by chonton** [comment]
Thanks for reporting this bug.

What is your expectation for the timestamp comparison?  Should any timestamp match?  Should a timestamp within the last X seconds match?

Snapshots were not an original design consideration since the snapshot repositories are mutable.

**Comment by chonton** [comment]
Please try version 0.7.0 to see if this satisfies your use case.
