### ISSUE TITLE
The artifact exists, but the plugin says otherwise

### ISSUE THREAD

**Issue by mikycol** [chonton/exists-maven-plugin#27]
I am trying to use the plugin to verify the existence of the artifact and prevent it from being re-published. I use the Job-Token as an authentication system, but I don't seem to be able to use it, any suggestions?

Thanks

**Comment by chonton** [comment]
Please add links that describe this authentication scheme.

**Comment by mikycol** [comment]
I'm looking at the deployment code to be able to give you better information (or in case send you a pull request), at the moment I have automated the publication of packages using this authentication method [https://docs.gitlab.com/ee/user/packages/maven_repository/#authenticate-with-a-ci-job-token-in-maven](url)
