### ISSUE TITLE
Did you intend to abandon Java 8 support?

### ISSUE THREAD

**Issue by jeremywall** [chonton/exists-maven-plugin#38]
I see the code changes to require Java 11 when using the plugin, what's the rationale behind that change? Java 8 still has almost 4 years left before it's EOL.

**Comment by chonton** [comment]
[End of Public Updates of Java SE 8](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)

"Java SE 8 has gone through the [End of Public Updates process](https://blogs.oracle.com/java-platform-group/end-of-public-updates-is-a-process%2c-not-an-event) for legacy releases.  Oracle will continue to provide free public updates and auto updates of Java SE 8 indefinitely for Personal, Development and other Users via [java.com](https://java.com/en/download/)."

As far I am concerned, java 8 **is** EOL.
