### ISSUE TITLE
Check if artifact exists in remote repository not working for test-jar

### ISSUE THREAD

**Issue by blinkdeveloper** [chonton/exists-maven-plugin#39]
Hi

First of all, I really like the idea behind the plugin and I have use cases where it is really helpful.

However, I have a problem with the following constellation:

We have Maven modules which expose code from the test scope (but they do not produce any main artifacts) by creating `test-jar` artifacts to use them in other modules, referenced with the `type` element:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
    <executions>
      <execution>
        <goals>
          <goal>test-jar</goal>
        </goals>
      </execution>
    </executions>
</plugin>
```

Let's call the artifact 'testArtifact'

In the Maven module where these test jars are used, let's call it `testApplication`, they are declared as dependencies:

```
<dependency>
  <groupId>some.groupId</groupId>
  <artifactId>testArtifact</artifactId>
  <version>${project.version}</version>
  <type>test-jar</type>
</dependency>
```

Because they need to be packaged into the resulting jar.

the `exists-maven-plugin` correctly identifies that the `testApplication` artifact already exists in the remote repository. However, because the deployment of the primary artifact is skipped (deploy.skip=true), Maven has some fallback behavior which results in this:

```
[exists-maven-plugin] some.groupId:testApplication:jar:version exists
[exists-maven-plugin] setting maven.deploy.skip=true
[exists-maven-plugin] Skipping artifact deployment
[maven] No primary artifact to deploy, deploying attached artifacts instead.
[maven] Uploading to ***-repository: https://nexus/content/repositories/release-repository/groupid/testArtifact/version/testArtifact.artifactId-version.pom
```

And then the build fails because it tries to deploy an artifact that already exists.

Do you have a suggestion how I can solve this problem? Or is this a bug?

**Comment by chonton** [comment]
This seems like a bug in maven-deploy-plugin.  Why should it deploy any artifacts if it has been told to skip deploy?

A workaround might be to configure the execution of maven-jar-plugin which creates the test-jar. Set the skip parameter to ${deploy.skip}

**Comment by blinkdeveloper** [comment]
> This seems like a bug in maven-deploy-plugin. Why should it deploy any artifacts if it has been told to skip deploy?

It does not deploy the artifact that it's told to skip, but because it skips the deployment of the primary artifact of testApplication, it apparently deploys whatever else is lying around. Whether that is a bug or not, I don't know.   

> A workaround might be to configure the execution of maven-jar-plugin which creates the test-jar. Set the skip parameter to ${deploy.skip}

This wouldn't help, because the problem does not occur when Maven processes the module of the test-jar, but when it processes the module which has a dependency to the test-jar.

**Comment by chonton** [comment]
If the test-jar was not deployed, would you have this problem?

**Comment by blinkdeveloper** [comment]
Well, I was curious if this could be handled by your plugin and extended it locally to test this :)

Short answer: yes!

How I implemented it:
- for each module, check whether a `maven-jar-plugin` execution with goal `test-jar` exists.
- if so, additionally check for the `-tests.jar` artifact
- if neither the main nor the tests JAR exist, deploy can be left to true
- if one of either exist, deploy should be skipped - this is the addition needed for my use-case

I had to add this check in `AbstractExistsMojo` and extend the `GAV` class a little.

The code is in very rudimentary shape :) So the question now would be:

1. Is that something you'd integrate into your plugin at all?
3. If so, is the information above enough for you or would you appreciate a PR?
4. Do you see any problems with that approach that I haven't thought of?
5. In case you'd appreciate a PR, I surely have to refactor the code somewhat, and add test cases. Unfortunately, out of the box, the integration tests did not work with my setup at all. 
6. I could also leave you a patch with what I've changed if that would help you integrate this feature the way that you want it to be.

**Comment by chonton** [comment]
I have been unsuccessful reproducing this issue.  Please create a small project that demonstrates the failure.

**Comment by blinkdeveloper** [comment]
Sure, see the attachment. I just removed the distributionManagement from the root POM.

You should be able to reproduce the issue by running:

```
mvn clean install
mvn deploy
mvn deploy
```

When the second deploy is executed, the following is the problem:

```
[main] [INFO] Checking for artifact at https://nexus/content/repositories/repository/exists/maven/plugin/demo/exists-maven-plugin-demo-test-sources
[exists-maven-plugin-demo.zip](https://github.com/chonton/exists-maven-plugin/files/10901884/exists-maven-plugin-demo.zip)
/1.0.1/exists-maven-plugin-demo-test-sources-1.0.1.jar
[main] [INFO] exists.maven.plugin.demo:exists-maven-plugin-demo-test-sources:jar:1.0.1 does not exist
```

Which is true, but not relevant, as the plugin should check if `exists-maven-plugin-demo-test-sources-1.0.1-tests.jar` already exists in the repository. 

I hope this helps, otherwise I'm glad help.
[exists-maven-plugin-demo.zip](https://github.com/chonton/exists-maven-plugin/files/10901889/exists-maven-plugin-demo.zip)

**Comment by blinkdeveloper** [comment]
Hi Chas

Were you able reproduce the problem? Please let me know if you are planning to adapt the plugin to handle this situation in the future, if you'd appreciate a PR or if I should just fork the plugin.

**Comment by chonton** [comment]
Try configuring the exists-maven-plugin's `project` to look for the test-jar.  Should be something 
like:
```xml
<configuration>
  <project>${project.groupId}:${project.artifactId}:test-jar:${project.version}</project>
</configuration>
 ```

**Comment by blinkdeveloper** [comment]
Thanks for your suggestion, but I don't think this works. According to the documentation, the 'test-jar' in your suggestion refers to the packaging. However, when using this:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <executions>
    <execution>
      <goals>
        <goal>test-jar</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

in a POM to create a test-jar of a module, this does not change the packaging of the artifact. It is still a JAR. But it changes the classifier to `tests`. Because of this, what happens when I try your suggestion is, that the plugin checks this URL:

`https://nexus/repository/com/example/<artifactName>/<version>/<artifactName>-<version>.test-jar`

while the correct URL would be: 

`https://nexus/repository/com/example/<artifactName>/<version>/<artifactName>-<version>-tests.jar`

But the `<project>` configuration is a good hint. 

If we could add the classifier to the `<project>` configuration, the problem could be solved, too. In contrast to the solution I outlined above, it requires extra configuration, but it is far less hacky, and I think adding some extra configuration for this corner case is justified.

Again, please let me know if you want to integrate this in your plugin, either yourself or with a contribution.

**Comment by chonton** [comment]
pull requests are welcome
