### ISSUE TITLE
Version 0.9.0 - cmpChecksum doesn't work when using Amazon S3

### ISSUE THREAD

**Issue by tobias-hammerschmidt** [chonton/exists-maven-plugin#41]
I think this is most likely the same root cause as in #37. The files are present and the scenario is working with version 0.5.0. Although version 0.8.0 fixes the access for the the artifact itself the checksum files still seem to be fetched with an extra / (being encoded as %2F in the request):

![image](https://github.com/chonton/exists-maven-plugin/assets/2543259/225fe9eb-1cab-4230-935e-e88b4f36016f)

**Comment by chonton** [comment]
try version 0.11.0

**Comment by tobias-hammerschmidt** [comment]
Still the same behavior in 0.11.0. Just had a look at the code - maybe https://github.com/chonton/exists-maven-plugin/blob/22e033ac34ca9b96b2111f12b2e359a400063797/src/main/java/org/honton/chas/exists/RemoteExistsMojo.java#L276 is missing the handling of leading slashes like in https://github.com/chonton/exists-maven-plugin/blob/22e033ac34ca9b96b2111f12b2e359a400063797/src/main/java/org/honton/chas/exists/RemoteExistsMojo.java#L263?

**Comment by chonton** [comment]
Thanks for the suggestion, please try 0.12.0

**Comment by tobias-hammerschmidt** [comment]
I can confirm that the scenario is working again with 0.12.0.
