### ISSUE TITLE
Not detecting artifacts with packaging maven-plugin

### ISSUE THREAD

**Issue by linesta-iti** [chonton/exists-maven-plugin#42]
It seems that, when the packaging of the project is different from `jar` and `pom`, this plugin does not work properly. 

I tried to use it with a maven plugin project , and for what I'm able to infer from the logs, it uses the project packaging as the file extension:

```
[INFO] 
[INFO] --- exists-maven-plugin:0.9.0:remote (default) @ distribution-maven-plugin ---
[INFO] Checking for artifact at https://repo.maven.apache.org/maven2/es/iti/commons/distribution-maven-plugin/1.0.2/distribution-maven-plugin-1.0.2.maven-plugin
[INFO] es.iti.commons:distribution-maven-plugin:maven-plugin:1.0.2 does not exist
```

Since the maven plugins are basically jar files, such *.maven-plugin file is abstent from the repository:

https://repo.maven.apache.org/maven2/es/iti/commons/distribution-maven-plugin/1.0.2/

and thus the plugin always will always decide that it does not exist.

**Comment by chonton** [comment]
Please try version 0.10.0

**Comment by linesta-iti** [comment]
Works fine with version 0.11.0 :+1: 

Thanks a lot for the fix!
