### ISSUE TITLE
failure with `Cannot invoke "String.length()" because "path" is null`

### ISSUE THREAD

**Issue by clembo590** [chonton/exists-maven-plugin#49]
# the issue with exists-maven-plugin

I believe The Failure is due to the fact that the plugin is looking for a `<distributionManagement>` section but this is not necessary to have it because this can actually be set in the maven settings.xml file as altReleaseDeploymentRepository. 

In order to reproduce exactly the issue easily I have created a branch on my repo:

`git clone https://github.com/clembo590/issues.git --branch issue_with_maven_exist_plugin`

run (note: you MUST modify of course the volume path to whatever folder you prefer)
`docker run -d -p 8081:8081 --name nexus -v  /Users/clement2/code/tutorials/dockervol/nexus sonatype/nexus3;`

run
`docker ps`
get the nexus containerId

run (of course replace the containerId by what you found previously)
`docker exec -it containerId sh;`

from within the docker container 
run `cat /nexus-data/admin.password`

copy the password and got to `http://localhost:8081`

sign in using `admin`/thePasswordYouJustCopied

once signed in 
through the wizard just create a user with `admin`/`admin`  (as user/pwd)

--> you are now good to go.

`mvn clean deploy`
--> it FAILS with ` Cannot invoke "String.length()" because "path" is null`

remove the `exists-maven-plugin` from the `pom.xml` file
run 
`mvn clean deploy`
--> it WORKS

**Comment by chonton** [comment]
1. The pom in the example, as given, does not include exists-maven-plugin.
2. What behavior do you expect with
     a. altReleaseDeploymentRepository specified as property?
     b. altReleaseDeploymentRepository specified as direct configuration of release plugin?

**Comment by chonton** [comment]
Thanks for your response.  I have several questions:

- Why are you using `altReleaseDeploymentRepository`? Is your "push" repository (specified by `altReleaseDeploymentRepository`) different than the "pull" repository (specified by `distributionManagement` element)?
- If "push" and "pull" repositories are the same, why use `altReleaseDeploymentRepository`?
- If "push" and "pull" repositories are different, which should exists-maven-plugin query?

**Comment by chonton** [comment]
It's unreasonable to expect not to update your pom after two years.  Vulnerabilities will have been detected and dependencies will need updating.

You can use properties in your distributionManagement element.  See [org.honton.chas.exists.it:parent](https://github.com/chonton/exists-maven-plugin/blob/master/src/it/remote/pom.xml#L28) for an example.

**Comment by chonton** [comment]
0.13.0 will issue error message if distributionManagement is not set when using the remote goal
