### ISSUE TITLE
Unable to change the artifact parameter from the command line

### ISSUE THREAD

**Issue by purpledrazi** [chonton/exists-maven-plugin#9]
I have a project with a custom packaging type, and the artifact that I publish does not use the packaging type as its suffix.

The default value of `${project.build.finalName}.${project.packaging}` for the artifact parameter is therefore not useful in this case.

The documentation suggests that I should be able to set the artifact name from the command line by passing, for example, `-Dartifact="${project.build.finalName}.pom"` but this has no effect.

I need to configure it on the command line, because I am trying to use this plugin to prevent attempting to overwrite previous releases, and of course there's no way to modify the pom of an old tagged release.

**Comment by purpledrazi** [comment]
I've just realised that I was mistaken about the documentation BTW - it doesn't say that it's possible to set the artifact from the command-line. 

It would be great if a mechanism to do this could be added.

**Comment by chonton** [comment]
Version 0.1.0 adds exists.artifact property
